version: "3.8"

x-immich-environment: &immich-env
  DB_HOSTNAME: ${DB_HOSTNAME}
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_DATABASE_NAME: ${DB_DATABASE_NAME}
  REDIS_HOSTNAME: ${REDIS_HOSTNAME}

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /mnt/nas/data/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nas/data/backups/richstorage/photos:/mnt/nas/photos:ro
      - /mnt/nas/data/backups/richstorage/videos:/mnt/nas/videos:ro
    environment:
      <<: *immich-env
    ports:
      - "2283:2283"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - /mnt/nas/data/immich-ml-cache:/cache
    environment:
      <<: *immich-env
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    restart: always

  redis:
    image: redis:6.2
    restart: always

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - /mnt/nas/docker/immich/pgdata:/var/lib/postgresql/data
    restart: always
