x-immich-environment: &immich-env
  DB_HOSTNAME: ${DB_HOSTNAME}
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_DATABASE_NAME: ${DB_DATABASE_NAME}
  REDIS_HOSTNAME: ${REDIS_HOSTNAME}

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /mnt/nas/data/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nas/data/backups/richstorage/photos:/mnt/nas/photos:ro
      - /mnt/nas/data/backups/richstorage/videos:/mnt/nas/videos:ro
    environment:
      <<: *immich-env
    ports:
      - "2283:2283"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
    restart: unless-stopped
    logging: *default-logging
    networks:
      - internal

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - /mnt/nas/data/immich-ml-cache:/cache
    environment:
      <<: *immich-env
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    restart: unless-stopped
    logging: *default-logging
    networks:
      - internal

  redis:
    image: redis:6.2
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging: *default-logging
    networks:
      - internal

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - /mnt/nas/docker/immich/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE_NAME} -U ${DB_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging: *default-logging
    networks:
      - internal

networks:
  internal:
